### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by ideag** [libreform/wp-libre-form#102]
A small gift for you guys - just point people to [http://gettryout.com/new/?template=libreform&provider=demo&redirect=wp-admin%2Fpost.php%3Fpost%3D4%26action%3Dedit](http://gettryout.com/new/?template=libreform&provider=demo&redirect=wp-admin%2Fpost.php%3Fpost%3D4%26action%3Dedit) and they will get a functioning WP site to test out how WP Libre Form woks.

**Comment by k1sul1** [comment]
Now we just need a domain "libreform.org" with subdomain demo that points to that.

**Comment by k1sul1** [comment]
We appreciate your generosity, but you're already doing a great deal to help the project. If you feel like you're rolling in money, we're not stopping you, but that really isn't necessary. 

If we ever decide to do a proper homepage, we might actually  need a domain, but for now I think that a "try it out" link in the README works :smiley_cat:
