### ISSUE TITLE
Form fields sanitized in MU when not super admin

### ISSUE THREAD

**Issue by timiwahalahti** [libreform/wp-libre-form#105]
Steps to reproduce:

1. Install WP Network
2. Create form as a super admin
3. Add new user with admin or editor role
4. Edit form with this new user
5. Ater save, there's no input fields

This is most probably because network installation is more strict about contents for content and is doing some additional sanitazion/stripping.

**Comment by k1sul1** [comment]
This is because by default, only super admins are capable of using unsanitized HTML. 

You need to allow it with a filter. Might be worth mentioning it in the README.

**Comment by timiwahalahti** [comment]
Yup, as I thought.

I'll do some digging and see if we can filter that out automatically when modifying forms. It would be the best solution.

**Comment by k1sul1** [comment]
I've one multisite running locally, I can take a shot at this.

**Comment by k1sul1** [comment]
This is a bit tricky. [Unfiltered MU](https://wordpress.org/plugins/unfiltered-mu/) works, but it's a dangerous solution that can't be used in a lot of cases.

I'm going to try adding the capability in save_post when the form is saved.

**Comment by k1sul1** [comment]
Impossibru to fix correctly on our side. Addressed in 2.0
