### ISSUE TITLE
Plugins page?

### ISSUE THREAD

**Issue by k1sul1** [libreform/wp-libre-form#109]
Since merging https://github.com/libreform/export to "core" is bit of an effort, and my builder plugin is finally starting to come together after 3 rewrites\* , I think that we need a plugins page inside `Forms`. 

A lot of people have complained to me about not being able to export, and when I've told them about the export plugin, they seem surprised. With a plugin page, we can guide more users to "official" plugins, and even 3rd party plugins based on some criteria\*2. We could provide a filter for letting normal plugins to register as WPLF plugins, and the plugins could have an easy way to creating options pages for their plugins, if said plugins need options.

*:` (Vue -> React + Dragula -> React + ReactDnD -> React + Kea)`
*2: `PR to this repository? n number of stars or a star from one of the maintainers on GitHub?`

**Comment by k1sul1** [comment]
And if we implement something like that, I suggest a one time admin notice about it in the version it comes out in.

**Comment by timiwahalahti** [comment]
Sounds like a good idea!
