### ISSUE TITLE
Update the plugin

### ISSUE THREAD

**Issue by luizbills** [libreform/wp-libre-form#111]
I'm using the version 1.4.3 and has a bug in submissions page. In "form filter" the select options appears without labels. But it is fixed in current version of master branch.

`1.4.3`: https://github.com/libreform/wp-libre-form/blob/1.4.3/classes/class-cpt-wplf-submission.php#L146
`master`: https://github.com/libreform/wp-libre-form/blob/master/classes/class-cpt-wplf-submission.php#L146

**Comment by k1sul1** [comment]
The master branch is... quite stable. You can use that in the meantime. Just test your forms, to be sure. 🙂 

I'm finally having some space on my schedule, let's see if I can get a release together this weekend, and the plugin updated.

In case anyone wants to help, feel free to checkout the master branch and merge pull requests marked with milestone 1.5 into it, and give a holler if it works.

There's also few bugs I'm going to fix. @libreform/maintainers, up for some PR reviews this weekend, or are you fine with me just merging the new and old PRs?

**Comment by k1sul1** [comment]
@luizbills does the 1.5 beta release work for you? 

In my initial tests it seems to work fine but I only have a handful of real world forms to test with.

**Comment by luizbills** [comment]
I will test today. I'll give you some feedback later.

**Comment by luizbills** [comment]
Has any breaking change on PHP or JS?

**Comment by k1sul1** [comment]
None that I know of. 

It might not run on older PHP versions (who knows?) since we "officially" only support 5.6 and beyond. There are some changes to the JS, but unless you specifically depended on a global variable with the name "main", you should be good. 

PHP is the "same", with new features and bug fixes, of course.
