### ISSUE TITLE
Disable Gutenberg editor when editing forms

### ISSUE THREAD

**Issue by samikeijonen** [libreform/wp-libre-form#126]
I was wondering if there is a way to disable Gutenberg editor when editing forms.

**Comment by timiwahalahti** [comment]
I'll work with this next Tuesday, while I have few other plugins to check also!

**Comment by timiwahalahti** [comment]
Did this a bit late, but Gutenberg is now disabled.

https://github.com/libreform/wp-libre-form/commit/a9db0b31a449315287167722439a80e3142ee319
