### ISSUE TITLE
Parse html form and create validation rules

### ISSUE THREAD

**Issue by luizbills** [libreform/wp-libre-form#136]
We can use some lib like https://github.com/Rct567/DomQuery to parse the HTML and create some validation rules.

e.g: `<input type="email" maxlength="20" required>`

this field is required (already implemented) and must be an valid email with 20 chars or less.

**Comment by rask** [comment]
You mean that the HTML would be parsed and backend (PHP) field validation would be built upon those HTML rules? Are there some rules which are not covered by the browser validation API (https://caniuse.com/#feat=form-validation)?

**Comment by k1sul1** [comment]
This seems stale, and IMO advanced validation is not in the scope of this project. Users can add their custom validators.

If anyone implements something like this, implement it as a standalone plugin, and I'll gladly feature it on the plugins page. I'm not willing to implement it myself, DOM operations & PHP make me want to go KMS.
