### ISSUE TITLE
Add a global settings page

### ISSUE THREAD

**Issue by luizbills** [libreform/wp-libre-form#139]
A global settings page for WP Libre Form it will be a good idea now that we have a plugins section. So all plugins can add their settings on this single page.

Optional: a simple settings api to easily add new fields.

**Comment by timiwahalahti** [comment]
IMO we do not need separate settings page or availability to do so.

**Comment by luizbills** [comment]
I was thinking in something like woocommerce settings page. A central of all plugins settings with a friendly API to easily add new settings.

**Comment by luizbills** [comment]
So we can recommend all plugin creators to use our Settings API to avoid having multiple settings pages in wp-admin.

**Comment by luizbills** [comment]
> We're already "recommending" authors to use `wplf()->plugins->register()`, so they won't have to pollute the menu with useless options pages. How said authors save data doesn't concern us. Some may want to use post_meta, and someone else might need to use custom tables or wp_options.

Oh sorry. I thought every author had to create his settings page if he used `wplf()->plugins->register()`.

**Comment by k1sul1** [comment]
#153 will introduce a settings page to bring backwards compatibility. There's no way to add fields to it though, other than editing our core code.
