### ISSUE TITLE
Better default subhmission title

### ISSUE THREAD

**Issue by luizbills** [libreform/wp-libre-form#156]
Currently the default title is **%name% <%email%>** (i guess). But I propose to make this a empty title and use **%form-title% #%submission-id%** as default title.

If my form is called "Contact Form", will generate automatically an submission with title: **Contact Form #1234**

**Comment by timiwahalahti** [comment]
This makes sense to me, we just need to make sure that there is some kind of default title if the form has no name.

@k1sul1 opinions?
@luizbills would you like to do PR?

**Comment by luizbills** [comment]
> ...we just need to make sure that there is some kind of default title if the form has no name.

Maybe **Submission** as default prefix/title.

@luizbills I have no time to PR, sorry.

**Comment by k1sul1** [comment]
I guess this is just a matter of setting the new default, as any forms that existed before that change have saved the value in a database, so changing it won't break anything.
