### ISSUE TITLE
TryoutWP demo - "database update required"

### ISSUE THREAD

**Issue by epicfaace** [libreform/wp-libre-form#165]
Related to #102 .

I have to click through a dialog, "Database update required".

![image](https://user-images.githubusercontent.com/1689183/54091928-4752f680-4343-11e9-9975-72857f394577.png)

**Comment by k1sul1** [comment]
@ideag I guess that you're using a db dump for the demo, and a recent update of WordPress causes this. If that's the case, updating the dump would probably fix this, but in any case, I think that this is a non-issue.
