### ISSUE TITLE
Fallback on no-js

### ISSUE THREAD

**Issue by timiwahalahti** [libreform/wp-libre-form#50]
Right now forms isn't working if used does not have javascript enabled. Yes, every website relies on js but I think when speaking about forms, it's quite important to have fallback.

We could just set form method to post, but that causes quite possibly conflict with post variable names since WordPress uses internally example `name` (full list of reserved variable names [here](http://wordpress.stackexchange.com/questions/77337/page-returns-404-with-post-variables-but-not-without).

One option is to prefix every input in code, so that user can just input `name="name"` in editor and it changes to `name="wplf_name"`. But I'm not sure if this is the way to go, because it's not that pretty, causes a lot of code changes and possibly breaks custom form handling made by user.

Other option is use get method, but then you can't send files and for pretty urls we need to handle form and make a redirect after that without any parameters.

And there's also a small problem with how and when to indicate success, using get parameter isn't a option because then user sends that url to friend... Yes, post parameter is answer. But we need also think form validation and validation error messages.

Yrgh :/

**Comment by k1sul1** [comment]
$0.02: 

We _could_ embed that list of reserved variable names on the editor screen, so that users at least know about it. Another option would be not to bug them about it, until they use a reserved word => tell the user what went wrong and how to fix. 

Prefixing is BS, and I'm pretty sure no one wants that. 

Success / Failure could be indicated with redirection to a user created thank you page.

**Comment by timiwahalahti** [comment]
I was a bit in a hurry and needed some solution quikly, so I made some [rough and nasty changes](https://github.com/timiwahalahti/wp-libre-form/tree/issue-50)...

Added also this few lines of code to the theme
```function dude_wplf_nojs_submit() {
  if( isset( $_POST['dude-name'] ) ) {
    wplf_ajax_submit_handler( true );
    $_POST['_wplf_success'] = true;
  }
}
add_action( 'init', 'dude_wplf_nojs_submit' );
```

So this does not make use of any proper validation for required fields and relies that user has prefixed input names, but it works as a dirty solution for now. Something more subtle is needed at least in some point.

**Comment by k1sul1** [comment]
Closing, as a PR for this already exists.
