### ISSUE TITLE
Integrate with WP REST API

### ISSUE THREAD

**Issue by k1sul1** [libreform/wp-libre-form#65]
Sooner or later, I or someone else is going to create a WordPress powered single page application and use this for forms. 

It shouldn't be too hard to provide the forms as JSON. Saving form entries could be a bit trickier. 

Instead of sending chunks of HTML, I propose the following syntax: 
```html
<form action="/">
  <div class="form-row">
    <input type="text" name="test">
  </div>
</form>
```

=>

```json
{
  "element": "form",
  "action": "/",
  "children": [
    {
      "element": "div",
      "class": "form-row",
      "children": [
        {
          "element": "input",
          "type": "text",
          "name": "test"
        }
      ]
    }
  ]
}
```

**Comment by anttiviljami** [comment]
I'm completely fine with an endpoint that would serve the form. 

`Accept: text/html` should return the form in regular old html
`Accept: application/json` could do something like what you're suggesting

**Comment by timiwahalahti** [comment]
At the same time we should change the sending from using admin-ajax.php to use rest api.

**Comment by k1sul1** [comment]
But how do we handle things like file uploads through the API? The "correct" way would be to create file upload endpoints for that but IMO that's over-engineering at finest.

**Comment by k1sul1** [comment]
I'll "rewrite" things to a proper REST API endpoint. The endpoint is going to accept form data and a JSON object, depending on the headers.
