### ISSUE TITLE
Register cpt without front

### ISSUE THREAD

**Issue by timiwahalahti** [libreform/wp-libre-form#73]
When registering cpt for forms, we should use
````
'rewrite' => array(
 'with_front' => false,
),
````

because in some rare cases, permalink structure contains also something else than data related to post, eg /blog/ something similar.

**Comment by anttiviljami** [comment]
can you elaborate? I think we need with_front to be true to allow for previews.

**Comment by timiwahalahti** [comment]
Nope, `with_front` is not needed for previews. It affects only the permalink structure for singular forms.

Lets say we have set custom permalink structure to be `/blog/%postname%`, this causes singular form preview addresses to be `/blog/libre-forms/%slug%`. With setting `with_front => false` we can get rid of that `/blog` part.

**Comment by timiwahalahti** [comment]
#93 relates to this. Will close, since fixing it will fix also this.
