### ISSUE TITLE
Allow loading form HTML from a HTML file

### ISSUE THREAD

**Issue by rask** [libreform/wp-libre-form#89]
Sometimes projects have static forms that work better when committed into project source code.

Would it be overkill to allow defining forms in a regular HTML file which would be imported to libre-form via a registration hook. Otherwise the form admin would be available but the form HTML field would be set to `readonly` with a note about which static HTML template file is being used in it.

If this would work better as a standalone plugin are the hooks in place to implement such a behavior and if not would it be OK to add those?

**Comment by k1sul1** [comment]
Sometimes? More like always :') 

I think registering forms from PHP is something that the "core"  should do, so I'm voting for that. If someone disagrees, surely we can at least add hooks for that.

**Comment by timiwahalahti** [comment]
I definitely agree that core should support usage of static forms from filesystem. Usage of version control system is good practice and wplf needs to support that.

@rask Would you like to make a PR?

**Comment by rask** [comment]
I will need to allocate some time to this but I can start working on this quite soon presumably.

**Comment by rask** [comment]
Oh this was left open. I'll close it.
